export const host = "http://localhost:8000/"
export const loginPath = "http://localhost:8000/auth/login"
export const regisPath = "http://localhost:8000/user"
export const getUserPath = "http://localhost:8000/auth/me"
export const contentPath = "http://localhost:8000/content"
export const updateNamePath = "http://localhost:8000/user/update"
